local function snakeToPascal(str)
    return (str:gsub("(%a)([%w_]*)", function(first, rest)
        return first:upper() .. rest:lower()
    end):gsub("_", ""))
end

local function getServiceFiles()
    local files = {}
    local isWindows = (package.config:sub(1,1) == "\\")
    -- Target the services directory directly or fallback to root recursive search
    local cmd = isWindows and "dir /s /b services\\*.lua 2>nul" or "find ./services -name '*.lua' 2>/dev/null"

    local p = io.popen(cmd)
    if p then
        for line in p:lines() do
            local cleanName = line:match("([^/\\]+)%.lua$")
            if cleanName then
                table.insert(files, { name = cleanName, path = line })
            end
        end
        p:close()
    end
    return files
end

local function GenerateMetaStubs()
    local services = {}

    for _, fileData in ipairs(getServiceFiles()) do
        local file = io.open(fileData.path, "r")
        if file then
            local content = file:read("*a")
            file:close()

            if content:find("%-%-%s*#service") then
                -- Match a class ending in Service, or fallback to converting snake_case filename
                local className = content:match("---@class%s+([%w_]+Service)") or snakeToPascal(fileData.name)
                table.insert(services, className); print(string.format("  [Found] %s -> %s", fileData.name, className))
            end
        end
    end

    local buffer = {
        "---@meta",
        "-- AUTO-GENERATED FILE, DO NOT EDIT MANUALLY; generated by gen_service.lua",
        "---@class LoadServiceFunction"
    }

    for _, serviceName in ipairs(services) do
        table.insert(buffer, string.format("---@field LoadService fun(self: MaxCore, serviceName: %q): %s", serviceName, serviceName))
    end
    table.insert(buffer, "---@field LoadService fun(self: MaxCore, serviceName: string): any")

    local metaFile = io.open("_services.d.lua", "w")
    if metaFile then
        metaFile:write(table.concat(buffer, "\n") .. "\n")
        metaFile:close()
        print(string.format("\27[32m[MetaGen]\27[0m Successfully wrote %d service stub(s) to _services.d.lua", #services))
    else
        print("\27[31m[MetaGen Error]\27[0m Could not open _services.d.lua for writing.")
    end
end

GenerateMetaStubs()
